In [1]:
import sys

sys.path.append('..')   # just in the context of this package

# look into PYTHONPATH

from BLogic import InputSpace, P, karnaugh_matrix
import numpy

In [4]:
S = InputSpace(4)

a, b, c, d = S(3), S(2), S(1), S(0)

M = karnaugh_matrix(4)

Display = numpy.vectorize(lambda x: 1 if x else 0)

Map = lambda a: print(*Display(a[M]), sep="\n", end=2*'\n')

print("Karnaugh Matrix:\n", *M, sep="\n", end=2*'\n')

print("a", "b", "c", "d", sep="\t", end=2*'\n')

P(a, b, c, d)

Karnaugh Matrix:

[ 0  2 10  8]
[ 1  3 11  9]
[ 5  7 15 13]
[ 4  6 14 12]

a	b	c	d

1	1	1	1
1	1	1	0
1	1	0	1
1	1	0	0
1	0	1	1
1	0	1	0
1	0	0	1
1	0	0	0
0	1	1	1
0	1	1	0
0	1	0	1
0	1	0	0
0	0	1	1
0	0	1	0
0	0	0	1
0	0	0	0


In [3]:
Map(a)
Map(b)
Map(c)
Map(d)

[1 1 1 1]
[0 0 0 0]
[0 0 0 0]
[1 1 1 1]

[1 0 0 1]
[1 0 0 1]
[1 0 0 1]
[1 0 0 1]

[1 1 1 1]
[1 1 1 1]
[0 0 0 0]
[0 0 0 0]

[1 1 0 0]
[1 1 0 0]
[1 1 0 0]
[1 1 0 0]

